version: "3"

services:
  ms-teams-app:
    container_name: ms-teams-app
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 
      " 
        echo 'Starting...' &&
        npm run-script start
      "
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app

